# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build-name
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install and start httpd
        run: sudo systemctl start apache2 && sudo systemctl status apache2
      - name: Get Runner host name
        id: step1
        run: echo "${{ runner.name }} - `hostname`" && echo test=`hostname` "$GITHUB_OUTPUT"
      - name: Curl
        run: curl http://`hostname`
      - name: Get IP Address
        run: curl -s https://api.ipify.org
      - name: Wait for sometime
        run: sleep 100 &
  build-run:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Curl
        run: sleep 2 && echo ${{needs.build-name.outputs.output1}} - echo ${{build-name.outputs.output1}} && curl http://${{needs.build.outputs.output1}}
