name: tmate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      run: sudo apt-get install tmate
    - name: Run
      run: tmate -F
